language: node_js
node_js:
  - "node"
cache:
  directories:
    - node_modules
branches:
  only:
    - master
script:
  - CI=false npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local_dir: build
  on:
    branch: master
  fqdn: poliglot.um.si
    #  fqdn: poliglot.feri.um.si
    #fqdn: poliglot.brokenpylons.com
