language: node_js
node_js:
  - "node"
cache:
  directories:
    - node_modules
branches:
  only:
    - master
script:
  - CI=false npm run build
after_success:
  - cp build/index.html build/200.html
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local_dir: build
  on:
    branch: master
  fqdn: poliglot.brokenpylons.com
